### PR TITLE
Added regression test for the sana empty file issue

### PR DESCRIPTION
**Pull request by bsipos**
Just added two tests as described in the title.

### CODE REVIEW

**Comment by shenwei356** [comment]
The new release passed bioconda test but failed [homebrew-bio](https://github.com/brewsci/homebrew-bio/pull/1074/checks?check_run_id=865344846), I guess because the `scat` test take too long (~3min).

**Comment by bsipos** [comment]
Interesting, would it eventually succeed if you gave it more time?

**Comment by shenwei356** [comment]
Nope, I can't control that process, not even rerun the test.

**Comment by bsipos** [comment]
We can always reduce the number of files written under the test directory, which will decrease runtime. It can be done by setting `SIZE=2`.

**Pull request merged**
