### PR TITLE
Finished the new "scat" subcommand and other additions

### PR DESCRIPTION
**Pull request by bsipos**
Hello Wei,

Time for a new merge request with the following additions/improvements:
- (Re)Added `scat`, a subcommand for real-time robust concatenation of fastx files. Large parts of it were rewritten and now it compiles on Windows. 🤞 It passes the tests I have added, so I think it is ready for a release. It might still encounter issues if files are concurrently created, moved, and renamed. However, those will probably resurface during "real world" use.
- Rewrote the parser behind the `sana` subcommand, now it supports robust parsing of fasta file as well. The parser is also used by the `scat` subcommand to stream records from multiple files.
- Added a "toolbox" feature to the `bam` subcommand (`-T`), which is a collection of filters acting on streams of BAM records configured through a YAML string (see the docs for more).
- Added a `SEQKIT_THREADS` environmental variable to override the default number of threads used (-1 means number of cores).
- For all these changes I have added a minimal documentation with examples.

### CODE REVIEW

**Comment by shenwei356** [comment]
Thank you @bsipos , can you please also add changelog to CHANGES.md?

**Comment by bsipos** [comment]
@shenwei356 Updated `CHANGES.md`, proposing a major release (v0.13.0).

**Comment by shenwei356** [comment]
There's a test error:

```
scat_fasta ran in 5 sec with 606/0 lines to STDERR/OUT
tests/sorted_scat_output.fas tests/sorted_scat_test_all.fas differ: byte 8, line 1
 FAIL "1" != "0" (LINE 622)
```

**Comment by bsipos** [comment]
This occurs to me as well. Bit busy at the moment but will fix it when time allows.

**Pull request merged**
