### PR TITLE
Added a sub-command for real time watching and streaming of fastx files. Rewrote sana backend.  

### PR DESCRIPTION
**Pull request by bsipos**
Hello Wei,

I have been working on a new subcommand (`scat`) which does "real-time" concatenation of fastx files written under a directory tree. This required a rewrite of the robust fastq/fasta parsers in the `sana` subcommand to support "following" files (just as `tail -f` does).
There are many things to iron out with the code, but the subcommand passed the basic tests and it is ready for your eyes.

The scat subcommand performs the following steps:
- Starts watching the input directory using fsnotify for new fastx files.
- Crawls the directory for existing fastx files and for each starts streaming the records using the robust parser backed.
- For each new fastx file reported a parser goroutine is started.
- The main thread pulls the parsed sequence records and prints them to the output file.
- The files are stopped being watched if an interrupt signal is received, a specified PID is no longer alive, or an inactivity limit is reached.
- A crawl-only mode (-f) is supported for parsing only exiting files.

I think this subcommand will be useful in general, but it will also specifically enable the real-time streaming and alignment of fastq records as they are being generated by the Oxford Nanopore basecallers.

Please have a look at the code if you got some time. More thorough testing to follow!
Best,
Botond

### CODE REVIEW

**Comment by shenwei356** [comment]
Thank you Botond!

I tried but it suspended after received interrupt signal (Ctrl + c). I also tried to find bug but failed.

**Comment by bsipos** [comment]
Hmmm. I suspect the cause of this issue. Did you send multiple Ctrl+Cs or just one? It can lock up with multiples but I think it is fixable.

**Comment by shenwei356** [comment]
There's also compile error for windows, You must consider supporting multiple platform.

```
--> windows/386 error: exit status 2
Stderr: # github.com/shenwei356/seqkit/seqkit/cmd
cmd/scat.go:200:15: undefined: syscall.Kill

--> windows/amd64 error: exit status 2
Stderr: # github.com/shenwei356/seqkit/seqkit/cmd
cmd/scat.go:200:15: undefined: syscall.Kill

```

Similar code can be found in  [rush](https://github.com/shenwei356/rush), but these part of code was implemented by [@bburgin](https://github.com/bburgin), it's beyond my ability.

**Comment by bsipos** [comment]
Yeah, I can take care of that. The fsnotify package is cross-platform and I can figure out signal handling on Windows. Will continue testing the code, it will take a while to finish this subcommand as the functionality is necessarily a bit convoluted. :)

**Pull request merged**
