### PR TITLE
Added an option to colorize the output of the seq subcommand.

### PR DESCRIPTION
**Pull request by bsipos**
Hello Wei,

This is a minor feature enabling ANSI colors for nucleotides, quality values and (when fixed) on amino acid residues in the output the seq subcommand using the (-k) flag.
There are some issues which need your help though:
- It seems that the detection of sequence type does not work or I cannot figure out how to use it properly. I used larger protein fasta files as input, yet the detected alphabet is DNA.
- For properly handling the ANSI colors on windows I would need to get access to the file descriptors in the xopen.Writer objects or use plain *os.File objects with bufio. Which option would you prefer?

Best,
Botond

### CODE REVIEW

**Comment by bsipos** [comment]
@shenwei356 Hi! I have switched from using xopen.Writer to io.Writer in seq.go so the TTY can be detected when using colors without exposing the file descriptors wrapped by xopen. So the second issue is solved. Regarding sequence type: nucleic acid colors are now the default and amino acid colros can be selected by specifying -t protein.

The colored fastq output now looks pretty slick, and as far as I am concerned this feature is ready for merging:

image

Cheers,
Botond

**Comment by shenwei356** [comment]
Thank you @bsipos , it's interesting and useful in some scenario. Windows supported?

**Comment by bsipos** [comment]
@shenwei356 Haven't tested on windows but will do so. It  should work as I wrap the stout in a go-colorable writer as you do for the logger.

**Comment by shenwei356** [comment]
Can't compile windows binaries, because the signal handle compatibility  haven't be fixed. :sweat_smile:

**Pull request merged**
