### PR TITLE
Fixed a bug causing sana hanging on empty files.

### PR DESCRIPTION
**Pull request by bsipos**
This PR fixes a fairly critical bug for the user of downstream pipelines as it causes sana to hang forever on empty input files.
Please issue a minor release if not too inconvenient after being reviewed/merged.

Thanks,
Botond

### CODE REVIEW

**Comment by shenwei356** [comment]
Are other commands sharing the same bug?

**Comment by shenwei356** [comment]
Better make sure master is up to date with the upstream before fixing new bugs.

```
git checkout master
git pull upstream master
git push origin master
```

**Comment by bsipos** [comment]
Oh sorry, I usually do that just forgot this time. :)

**Comment by bsipos** [comment]
> Are other commands sharing the same bug?

No, the bug was in the sana parser - so only affects sana and scat.

**Pull request merged**
