### PR TITLE
Minor fix in the BAM toolbox

### PR DESCRIPTION
**Pull request by bsipos**
Minor fix in the BAM toolbox adding the field "RightSoftClipSeq".

### CODE REVIEW

**Comment by shenwei356** [comment]
Seems that you have not synced your fork for a long long time.

**Comment by shenwei356** [comment]
Oh right, don't forget record the changes in CHANGES.md :)

**Comment by bsipos** [comment]
@shenwei356 Synced that fork now. :) By the way, could you issue a minor release with this fix if it is not too much trouble?
It adds no new features so I am not sure if it is worth explicitly mentioning it in CHANGES.md.

**Comment by shenwei356** [comment]
Ofcouse it is worth explicitly mentioning it in CHANGES.md. 
I'll relase it some day in this week, a little busy recently.

**Comment by bsipos** [comment]
Okay, thanks in advance!

**Pull request merged**
